services:
 mu_ag:
  build:
   context: .

  container_name: ${mu_ag_HOSTNAME:-mu_ag}

  hostname: ${mu_ag_HOSTNAME:-mu_ag}

  expose:
    - ${mu_ag_INTERNAL_PORT:-4000}

  ports:
   - ${mu_ag_EXPOSED_PORT:-4000}:4000

  environment:
    GROUPS_API: http://${mu_groups_ms_HOSTNAME:-mu_groups_ms}:${mu_groups_ms_EXPOSED_PORT:-8008}/api
    AUTH_API: http://${mu_auth_ms_HOSTNAME:-mu_auth_ms}:${mu_auth_ms_INTERNAL_PORT:-5000}


include:
  # Groups MS
  - path: groups_ms/docker-compose.yml
    project_directory: groups_ms/

  # Auth MS
  - path: auth/docker-compose.yml
    project_directory: auth/