services:
 mu_ag:
  build:
   context: .

  container_name: ${mu_ag_HOSTNAME:-mu_ag}

  hostname: ${mu_ag_HOSTNAME:-mu_ag}

  expose:
    - ${mu_ag_INTERNAL_PORT:-4000}

  ports:
   - ${mu_ag_EXTERNAL_PORT:-4000}:${mu_ag_INTERNAL_PORT:-4000}

  environment:
    GROUPS_MS: http://${mu_groups_ms_HOSTNAME:-mu_groups_ms}:${mu_groups_ms_INTERNAL_PORT:-8008}/api
    AUTH_MS: http://${mu_auth_ms_HOSTNAME:-mu_auth_ms}:${mu_auth_ms_INTERNAL_PORT:-5000}
    BULK_MS: http://${mu_bulk_ms_HOSTNAME:-mu_bulk_ms}:${mu_bulk_ms_INTERNAL_PORT:-8080}/api
    USERS_MS: http://${mu_users_ms_HOSTNAME:-mu_users_ms}:${mu_users_ms_INTERNAL_PORT:-8008}/api/users
    CATEGORIES_MS: http://${mu_categories_ms_HOSTNAME:-mu_categories_ms}:${mu_categories_ms_INTERNAL_PORT:-8001}/api/categories


include:
  # Groups MS
  - path: groups_ms/docker-compose.yml
    project_directory: groups_ms/

  # Auth MS
  - path: auth/docker-compose.yml
    project_directory: auth/

  # Bulk MS
  - path: bulk_ms/docker-compose.yml
    project_directory: bulk_ms/

  # Users MS
  - path: users_ms/docker-compose.yml
    project_directory: users_ms/

  # Categories MS
  - path: categories_ms/docker-compose.yml
    project_directory: categories_ms/
